SELECT 'hello, SQLite';

CREATE TABLE Fleet (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT
);

CREATE TABLE Ships (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT,
  DateBuilt TEXT,
  FleetID INTEGER,
  FOREIGN KEY (FleetID) REFERENCES Fleet(ID)
);

CREATE TABLE Sailors (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT,
  BirthDate TEXT
);

CREATE TABLE Duties (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Description TEXT
);

CREATE TABLE Ranks (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  Title TEXT
);

CREATE TABLE TourOfDuty (
  StartDate TEXT,
  EndDate TEXT,
  ShipID INTEGER,
  SailorID INTEGER,
  DutyID INTEGER,
  RankID INTEGER,
  FOREIGN KEY (ShipID) REFERENCES Ships(ID),
  FOREIGN KEY (SailorID) REFERENCES Sailors(ID),
  FOREIGN KEY (DutyID) REFERENCES Duties(ID),
  FOREIGN KEY (RankID) REFERENCES Ranks(ID)
);
